In [2]:
import pandas as pd

df = pd.read_csv("listings.csv.gz", compression="gzip")

df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20260614073253,2026-06-15,city scrape,11 Min to Manhattan • Prospect Park • Fast WiFi,"Bright, serene room in a renovated apartment h...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,2787,...,5.00,4.78,4.78,NaN,NaN,5,0,5,0,0.08
1,6848,https://www.airbnb.com/rooms/6848,20260614073253,2026-06-14,city scrape,Only 2 stops to Manhattan studio,Comfortable studio apartment with super comfor...,NaN,https://a0.muscache.com/pictures/e4f031a7-f146...,15991,...,4.80,4.69,4.59,NaN,NaN,1,1,0,0,0.95
2,6872,https://www.airbnb.com/rooms/6872,20260614073253,2026-06-14,city scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,16104,...,5.00,5.00,5.00,NaN,NaN,2,0,2,0,0.04
3,6990,https://www.airbnb.com/rooms/6990,20260614073253,2026-06-14,city scrape,UES Beautiful Blue Room,Beautiful peaceful healthy home,NaN,https://a0.muscache.com/pictures/45fb4ec7-6856...,16800,...,4.94,4.85,4.84,NaN,NaN,1,0,1,0,1.24
4,7097,https://www.airbnb.com/rooms/7097,20260614073253,2026-06-14,city scrape,"Perfect for Your Parents, With Garden & Patio",Parents/grandparents coming to town or are you...,NaN,https://a0.muscache.com/pictures/aaac19fc-4b4d...,17571,...,4.93,4.95,4.82,NaN,NaN,2,0,2,0,2.12

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30259 entries, 0 to 30258
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            30259 non-null  int64
 1   listing_url                                   30259 non-null  object
 2   scrape_id                                     30259 non-null  int64
 3   last_scraped                                  30259 non-null  object
 4   source                                        30259 non-null  object
 5   name                                          30258 non-null  object
 6   description                                   29357 non-null  object
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   30259 non-null  object
 9   host_id                                       30259 non-null  int64
 10  host_url                                      30259 non-null  object
 11  host_profile_id                               29910 non-null  float64
 12  host_profile_url                              29910 non-null  object
 13  host_name                                     29910 non-null  object
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      29910 non-null  float64
 16  hosts_time_as_user_months                     29910 non-null  float64
 17  hosts_time_as_host_years                      29910 non-null  float64
 18  hosts_time_as_host_months                     29910 non-null  float64
 19  host_location                                 23097 non-null  object
 20  host_about                                    17849 non-null  object
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             29910 non-null  object
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              29910 non-null  object
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           29910 non-null  float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          29910 non-null  object
 32  host_identity_verified                        29910 non-null  object
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        30259 non-null  object
 35  neighbourhood_group_cleansed                  30259 non-null  object
 36  latitude                                      30259 non-null  float64
 37  longitude                                     30259 non-null  float64
 38  property_type                                 30259 non-null  object
 39  room_type                                     30259 non-null  object
 40  accommodates                                  30259 non-null  int64
 41  bathrooms                                     20147 non-null  float64
 42  bathrooms_text                                30100 non-null  object
 43  bedrooms                                      19286 non-null  float64
 44  beds                                          20839 non-null  float64
 45  amenities                                     30259 non-null  object
 46  price                                         21515 non-null  object
 47  price_quote_checkin_date                      22678 non-null  object
 48  price_quote_checkout_date                     22678 non-null  object
 49  price_quote_total_price                       21514 non-null  float64
 50  price_quote_price_per_night                   21514 non-null  float64
 51  price_quote_raw                               22678 non-null  object
 52  minimum_nights                                30257 non-null  float64
 53  maximum_nights                                30257 non-null  float64
 54  minimum_minimum_nights                        30257 non-null  float64
 55  maximum_minimum_nights                        30257 non-null  float64
 56  minimum_maximum_nights                        30257 non-null  float64
 57  maximum_maximum_nights                        30257 non-null  float64
 58  minimum_nights_avg_ntm                        30259 non-null  float64
 59  maximum_nights_avg_ntm                        30259 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              29912 non-null  object
 62  availability_30                               30259 non-null  int64
 63  availability_60                               30259 non-null  int64
 64  availability_90                               30259 non-null  int64
 65  availability_365                              30259 non-null  int64
 66  calendar_last_scraped                         30259 non-null  object
 67  number_of_reviews                             30259 non-null  int64
 68  number_of_reviews_ltm                         30259 non-null  int64
 69  number_of_reviews_l30d                        30259 non-null  int64
 70  availability_eoy                              30259 non-null  int64
 71  number_of_reviews_ly                          30259 non-null  int64
 72  estimated_occupancy_l365d                     30259 non-null  int64
 73  estimated_revenue_l365d                       21515 non-null  float64
 74  first_review                                  21700 non-null  object
 75  last_review                                   21700 non-null  object
 76  review_scores_rating                          21700 non-null  float64
 77  review_scores_accuracy                        21694 non-null  float64
 78  review_scores_cleanliness                     21700 non-null  float64
 79  review_scores_checkin                         21692 non-null  float64
 80  review_scores_communication                   21697 non-null  float64
 81  review_scores_location                        21691 non-null  float64
 82  review_scores_value                           21691 non-null  float64
 83  license                                       5286 non-null   object
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                30259 non-null  int64
 86  calculated_host_listings_count_entire_homes   30259 non-null  int64
 87  calculated_host_listings_count_private_rooms  30259 non-null  int64
 88  calculated_host_listings_count_shared_rooms   30259 non-null  int64
 89  reviews_per_month                             21700 non-null  float64
dtypes: float64(42), int64(18), object(30)
memory usage: 20.8+ MB

In [4]:
df.describe(include="all")

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,3.025900e+04,30259,3.025900e+04,30259,30259,30258,29357,0.0,30259,3.025900e+04,...,21697.000000,21691.000000,21691.000000,5286,0.0,30259.000000,30259.000000,30259.000000,30259.000000,21700.000000
unique,NaN,30259,NaN,4,2,28835,24173,NaN,29608,NaN,...,NaN,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,https://www.airbnb.com/rooms/1707074575928715496,NaN,2026-06-14,city scrape,Water View King Bed Hotel Room,You'll have a great time at this comfortable p...,NaN,https://a0.muscache.com/pictures/6998e77e-4564...,NaN,...,NaN,NaN,NaN,Exempt,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1,NaN,14356,21461,30,167,NaN,35,NaN,...,NaN,NaN,NaN,2956,NaN,NaN,NaN,NaN,NaN,NaN
mean,6.172513e+17,NaN,2.026061e+13,NaN,NaN,NaN,NaN,NaN,NaN,2.672815e+15,...,4.821284,4.743640,4.633094,NaN,NaN,55.887141,45.630721,9.146601,0.095905,0.846505
std,6.155147e+17,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,6.705743e+16,...,0.418090,0.388374,0.496439,NaN,NaN,174.246090,172.331916,36.412035,1.125182,1.847935
min,2.539000e+03,NaN,2.026061e+13,NaN,NaN,NaN,NaN,NaN,NaN,1.678000e+03,...,0.000000,0.000000,0.000000,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,3.038760e+07,NaN,2.026061e+13,NaN,NaN,NaN,NaN,NaN,NaN,2.069159e+07,...,4.820000,4.660000,4.530000,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.090000
50%,6.608782e+17,NaN,2.026061e+13,NaN,NaN,NaN,NaN,NaN,NaN,1.074344e+08,...,4.960000,4.850000,4.760000,NaN,NaN,2.000000,1.000000,0.000000,0.000000,0.270000
75%,1.160901e+18,NaN,2.026061e+13,NaN,NaN,NaN,NaN,NaN,NaN,3.948700e+08,...,5.000000,5.000000,4.920000,NaN,NaN,12.000000,3.000000,2.000000,0.000000,0.962500
max,1.707075e+18,NaN,2.026061e+13,NaN,NaN,NaN,NaN,NaN,NaN,1.704453e+18,...,5.000000,5.000000,5.000000,NaN,NaN,955.000000,955.000000,231.000000,22.000000,115.630000

In [5]:
df.isna().sum().sort_values(ascending=False)

neighborhood_overview                           30259
host_since                                      30259
host_response_time                              30259
host_thumbnail_url                              30259
host_acceptance_rate                            30259
                                                ...
availability_30                                     0
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
Length: 90, dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.columns.tolist()

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_profile_id',
 'host_profile_url',
 'host_name',
 'host_since',
 'hosts_time_as_user_years',
 'hosts_time_as_user_months',
 'hosts_time_as_host_years',
 'hosts_time_as_host_months',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'price_quote_checkin_date',
 'price_quote_checkout_date',
 'price_quote_total_price',
 'price_quote_price_per_night',
 'price_quote_raw',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'availability_eoy',
 'number_of_reviews_ly',
 'estimated_occupancy_l365d',
 'estimated_revenue_l365d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

In [8]:
print(df["neighbourhood_group_cleansed"].value_counts(dropna=False))

neighbourhood_group_cleansed
Manhattan        13709
Brooklyn         10562
Queens            4680
Bronx              976
Staten Island      332
Name: count, dtype: int64

In [9]:
print(df["neighbourhood_cleansed"].head(20))

0             Kensington
1           Williamsburg
2            East Harlem
3            East Harlem
4            Fort Greene
5           Williamsburg
6            Fort Greene
7                 Harlem
8        Upper West Side
9       Theater District
10       Upper East Side
11       Lower East Side
12    Financial District
13             Rego Park
14              Flatbush
15    Bedford-Stuyvesant
16        Hell's Kitchen
17                Harlem
18               Astoria
19                Harlem
Name: neighbourhood_cleansed, dtype: object

In [10]:
columns_to_drop = [
    "neighborhood_overview",
    "host_since",
    "host_response_time",
    "host_response_rate",
    "host_acceptance_rate",
    "host_thumbnail_url",
    "host_neighbourhood",
    "host_total_listings_count",
    "host_verifications",
    "neighbourhood",
    "calendar_updated",
    "instant_bookable"
]

df = df.drop(columns=columns_to_drop)

df.shape

(30259, 78)

In [11]:
df["price"] = (
    df["price"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["price"] = pd.to_numeric(df["price"])

In [12]:
df["price"].head()

0    113.97
1    117.27
2     80.06
3     77.17
4    202.47
Name: price, dtype: float64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df["price"].isna().sum()

np.int64(8744)

In [15]:
df = df.dropna(subset=["price"])

df.shape

(21515, 78)

In [16]:
df["price"].describe()

count    21515.000000
mean       278.229518
std        531.730477
min          4.580000
25%         96.875000
50%        174.690000
75%        302.720000
max      30972.960000
Name: price, dtype: float64

In [17]:
df = df[(df["price"] >= 25) & (df["price"] <= 3000)]

df["price"].describe()

count    21370.000000
mean       254.599714
std        271.939050
min         25.190000
25%         97.000000
50%        174.295000
75%        300.137500
max       2967.060000
Name: price, dtype: float64

In [33]:
df.shape

(21370, 78)